name: Build Linux Distribution Packages

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-debian-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libncurses-dev dpkg-dev debhelper

      - name: Build Debian package
        run: |
          # Create build directory
          mkdir -p build-debian
          cd build-debian
          
          # Configure with CMake
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr
          make -j$(nproc)
          
          # Run tests
          ctest
          
          # Prepare for packaging
          mkdir -p cli-file-explorer-${{ github.ref_name || 'dev' }}/usr/bin
          cp cli_file_explorer cli-file-explorer-${{ github.ref_name || 'dev' }}/usr/bin/
          
          # Copy debian directory
          cp -r ../debian cli-file-explorer-${{ github.ref_name || 'dev' }}/
          
          # Build the package
          cd cli-file-explorer-${{ github.ref_name || 'dev' }}
          dpkg-buildpackage -us -uc -b

      - name: Upload Debian package
        uses: actions/upload-artifact@v3
        with:
          name: debian-package
          path: build-debian/*.deb

  build-arch-package:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm cmake make gcc ncurses git binutils

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Arch Linux package
        run: |
          # Create build directory
          mkdir -p build-arch
          cd build-arch
          
          # Copy PKGBUILD to a working directory
          mkdir -p cli-file-explorer
          cp ../PKGBUILD cli-file-explorer/
          cd cli-file-explorer
          
          # Build the package
          makepkg -f --noconfirm
          
          # Verify package creation
          ls -la

      - name: Upload Arch package
        uses: actions/upload-artifact@v3
        with:
          name: arch-package
          path: build-arch/cli-file-explorer/*.pkg.tar.zst